# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx
# description will be included in the image's metadata
description: This is my custom Bazzite image that tries to add all the development capabilities from the Bluefin DX image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/bluefin-cli /usr/bin/atuin /usr/bin/atuin
      - COPY --from=ghcr.io/ublue-os/bluefin-cli /usr/share/bash-prexec /usr/share/bash-prexec

  - type: files
    files:
      - ../bluefin/system_files/shared/: /
      - ../bluefin/system_files/kinoite/: /
      - ../bluefin/system_files/dx/: /

# Activate RPM Fusion repos
  - type: script
    scripts:
      - copr-repos.sh

# Install packages from Bluefin and Bluefin DX
  - from-file: packages.yml

# Install Starhip and activate RPM Fusion repos
  - type: script
    scripts:
      - fetch-install.sh
      - ../bluefin/build_files/base/fetch-quadlets.sh

# alternatives cannot create symlinks on its own during a container build
  - type: script
    snippets:
      - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld"

# Install fonts
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

# Enable systemd services
  - type: systemd
    system:
      enabled:
        - rpm-ostree-countme.service
        # - dconf-update.service Already in Bazzite
        - docker.socket
        - podman.socket
        - swtpm-workaround.service
    user:
      enabled:
        - podman-auto-update.timer

# Cleanup repos, etc...
  - type: script
    snippets:
      - "FEDORA_MAJOR_VERSION=${OS_VERSION}"
    scripts:
      - ../bluefin/build_files/base/cleanup.sh
      - ../bluefin/build_files/dx/cleanup-dx.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

