# image will be published to ghcr.io/<user>/<name>
name: bazzite-dx
# description will be included in the image's metadata
description: This is my custom Bazzite image that tries to add all the development capabilities from the Bluefin DX image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
# Copy Bluefin-CLI
  - type: copy
    from: ghcr.io/ublue-os/bluefin-cli
    src: /usr/bin/atuin
    dest: /usr/bin/atuin
  - type: copy
    from: ghcr.io/ublue-os/bluefin-cli
    src: /usr/share/bash-prexec
    dest: /usr/share/bash-prexec

# Activate RPM Fusion repos
  - type: script
    scripts:
      - copr-repos.sh

# Install packages from Bluefin and Bluefin DX
  - from-file: packages.yml

# Install Starhip
  - type: script
    snippets:
      - "curl -Lo /tmp/starship.tar.gz 'https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz'"
      - "tar -xzf /tmp/starship.tar.gz -C /tmp"
      - "install -c -m 0755 /tmp/starship /usr/bin"
      - "# shellcheck disable=SC2016"
      - "echo 'eval \"$(starship init bash)\"' >> /etc/bashrc"

# alternatives cannot create symlinks on its own during a container build
  - type: script
    snippets:
      - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld"

# Activate RPM Fusion repos
  - type: script
    scripts:
      - quadlets.sh

# Install fonts
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

# Enable systemd services
  - type: systemd
    system:
      enabled:
        - rpm-ostree-countme.service
        # - dconf-update.service Already in Bazzite
        - docker.socket
        - podman.socket
        - swtpm-workaround.service
    user:
      enabled:
        - podman-auto-update.timer

# Cleanup repos, etc...
  - type: script
    scripts:
      - cleanup.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

